### ISSUE TITLE
Can you support some system of custom modifiers that can modify the link?

### ISSUE THREAD

**Issue by nikitavoloboev** [deanishe/alfred-searchio#37] opened 2018-01-29 00:29 UTC
Similar to [Safari Assistant](https://github.com/deanishe/alfred-safari-assistant) which lets you define custom actions for modifier actions.

It would be amazing if you can do the same for Searchio. 

For example I would love to combine `DuckDuckGo` search with an additional modifier that would prefix my search result query with `!ducky` which is [DuckDuckGo's alternative to Google Feeling Lucky](https://duck.co/forum/thread/4698/google-s-feeling-lucky). Or combine Google search with Google feeling lucky so you can do both searches from one script filter. On return, open web page with google results and with `⌃ + ⏎` activate `Google Lucky` on the search query. 

I hope something like this would be possible, this would make Searchio perfect. Thank you.

**Comment by deanishe** [comment] 2018-01-29 01:44
This is largely a duplicate of #15 (which you created).

Now, as then, I'm not at all sold on the idea. It would require *a lot* of work to implement, and the payoff seems very minor.

**Closed by deanishe** 2018-01-29 01:44 UTC

**Comment by nikitavoloboev** [comment] 2018-07-30 09:47
I will try to look into this myself and if won't accept the PR will just keep a fork of Searchio.

I just find it annoying to have to keep two separate searches (one for normal Google and one for Google lucky). I also wish to do the same for DuckDuckGo with its own lucky search so I can access those with cmd+return.

Hopefully I can manage to modify this workflow to suit this use case in good way. And if not I will probably create a small workflow just for those two searches I will be using. And will reuse the logic for making the searches fast from Go ver. of the workflow.

**Comment by nikitavoloboev** [comment] 2018-07-30 09:59
Aside from those google lucky searches, it would be also be great to extend Google query with searches scoped to some date. `i.e. Past month`. I am thinking of solving this with variables perhaps. Have each generated search get some unique ID and then with variables extend what the search will do on each of the modifier presses.

i.e. Google search can get ID: `100` so in Configuration sheet you can create variable `100_CMD` and give it value of `http://www.google.com/search?hl=en&q={query}&btnI=I`.

Would this work?

**Comment by deanishe** [comment] 2018-07-30 10:37
> Have each generated search get some unique ID and then with variables extend what the search will do on each of the modifier presses.

They already have unique IDs. How do you think it works? Have you even looked at the code?

The complexity lies in making each saved search support multiple engines and altering the UI to make creating them possible.

*Please* stop asking me questions you could easily answer yourself by looking at the code. I know you can read the code. You're just being lazy.

**Comment by nikitavoloboev** [comment] 2018-07-30 10:44
> You're just being lazy

You are right. I should of studied the code first before asking. Just wanted to throw some thoughts I had first before trying to implement something. Should stop doing that and get into the habit of reading code first.

I will try and play with this idea and see if I can make something work. Apologize for the noise.
